[project]
name = "5580-dm-a3-association"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ruff>=0.14.14",
    "ty>=0.0.14",
]
